Some Improvements
ilyatos/uptime-monitor pull request #10
Opened 2018-10-30 11:02 UTC by ilyatos

2018-10-30 11:51 UTC, n0str requested changes

2018-10-30 11:51 UTC, n0str commented on app/monitor/Helpers/RequestToService.php
> +    const REQUEST_TIMEOUT = 5;
Можно брать из env при ините

2018-10-30 11:51 UTC, n0str commented on app/monitor/Modules/ResponseTime.php
> +    const TIME_ERROR = 0.3;
тоже из ENV

2018-10-30 11:51 UTC, n0str commented on app/monitor/Monitor.php
> +            $this->runForOne($service);
А чего ты убрал try то? У нас тогда если один сервис грохнется - дальше прекратится выполнение.

2018-10-30 11:54 UTC, ilyatos commented on app/monitor/Monitor.php
> +            $this->runForOne($service);
Я же добавил в самом верху обработчик, разве не продолжится работа, после того, как я обработаю наверху?

2018-10-31 16:27 UTC, ilyatos commented on app/monitor/Helpers/RequestToService.php
> +    const REQUEST_TIMEOUT = 5;
Это как вообще?

2018-10-31 19:34 UTC, n0str approved these changes

2018-10-31 19:34 UTC, merged